
// for create and update, we can use the same DTO since the fields are the same. 
// The only difference is that for update, we will require the id field to identify 
// which record to update. For create, the id will be generated by the database, so 
// it can be optional or not included in the DTO at all. However, if we want to keep 
// the DTOs separate for clarity and future extensibility, we can do so as well. In this case,
//  I have included the id field in the CreateDebitAdviceDto as optional, but it can be removed if you prefer to keep it strictly for updates.
import { Type } from 'class-transformer';
import { ValidateNested, IsArray, ArrayMinSize, IsNumber, IsString, IsDateString, IsNotEmpty } from 'class-validator';
import { DebitAdviceLineItemDto } from "./CreateDebitAdviceLineItemDto";
import { isDate } from 'util/types';

export class CreateDebitAdviceDto {

    @IsNumber()
    id?: number;

    @IsNumber()
    created_by?: number;

    @IsString()
    document_number: string;

    @IsDateString()
    transaction_date: string;

    @IsNumber()
    quarter: number;

    @IsArray()
    @ArrayMinSize(1)
    @ValidateNested({ each: true })
    @Type(() => DebitAdviceLineItemDto)
    line!: DebitAdviceLineItemDto[];
    access_key_id?: number;
    createdBy?: number;
}

