
// for create and update, we can use the same DTO since the fields are the same. 
// The only difference is that for update, we will require the id field to identify 
// which record to update. For create, the id will be generated by the database, so 
// it can be optional or not included in the DTO at all. However, if we want to keep 
// the DTOs separate for clarity and future extensibility, we can do so as well. In this case,
//  I have included the id field in the CreateDebitAdviceDto as optional, but it can be removed if you prefer to keep it strictly for updates.
import { Type } from 'class-transformer';
import { ValidateNested, IsArray, ArrayMinSize, IsNumber, IsString, IsDateString, IsNotEmpty, IsOptional } from 'class-validator';
import { UpdateDebitAdviceLineItemDto } from "./UpdateDebitAdviceLineItemDto";
import { isDate } from 'util/types';

export class UpdateDebitAdviceDto {


    @IsNumber()
    status_id?: number;

    @IsString()
    document_number: string;

    @IsDateString()
    updated_at: string;

    @IsNumber()
    isdeleted: number; // flag to indicate if the item is marked for deletion



    @IsArray()
    @ArrayMinSize(1)
    @ValidateNested({ each: true })
    @Type(() => UpdateDebitAdviceLineItemDto)
    line!: UpdateDebitAdviceLineItemDto[];
    access_key_id?: number;

    @IsOptional()
    createdBy?: number;

    @IsOptional()
    transaction_date?: string;

    @IsOptional()
    quarter?: number;
}

